### ISSUE TITLE
Plugin does not Update

### ISSUE THREAD

**Issue by peterloudon** [ggoulf/CRMGG.ExchangeRates#1]
Installed Version : 1.2017.7.13
Latest Version : 1.2017.7.14

Selecting for Install changes nothing. The versions stay as listed and the plugin is not updated. No errors occur and no error messages are generated.

**Comment by ggoulf** [comment]
sorry, it was an error on the nugget package, the dll version was 1.2017.7.13 on the package 1.2017.7.14.
Should be ok with the new version.
